name: pearson demo
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  tests-v10:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress info
        uses: ./
        with:
          # just for full picture after installing Cypress
          # print information about detected browsers, etc
          # see https://on.cypress.io/command-line#cypress-info
          build: npx cypress info
          working-directory: cypress

      - name: Chrome headless
        uses: ./
        with:
          working-directory: cypress
          browser: chrome
          headless: true

      - uses: actions/upload-artifact@v2
        with:
          name: screenshots-in-headless-chrome
          path: cypress/screenshots

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: chrome
