name: pearson demo
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start

      - name: Chrome headless
        uses: ./.github/workflows/demo.yml
        with:
          working-directory: cypress
          browser: chrome
          headless: true

      - uses: actions/upload-artifact@v2
        with:
          name: screenshots-in-headless-chrome
          path: cypress/screenshots

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: chrome
